### ISSUE TITLE
Error while evaluate wechat-uos due to openssl insecure

### ISSUE THREAD

**Issue by Cryolitia** [xddxdd/nur-packages#21]
```
error: Package ‘openssl-1.1.1u’ in /nix/store/7gk6gfyv4sdwm2iyxwvph51nq4bp829p-nixos/nixos/pkgs/development/libraries/openssl/default.nix:210 is marked as insecure, refusing to evaluate.


       Known issues:
        - OpenSSL 1.1 is reaching its end of life on 2023/09/11 and cannot be supported through the NixOS 23.05 release cycle. https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
```

**Comment by xddxdd** [comment]
Unfortunately there is no better way than explicitly agreeing to use OpenSSL 1.1 (and Electron 19):

```
{
  nixpkgs.config.permittedInsecurePackages = [
    "electron-19.0.7"
    "openssl-1.1.1u"
  ];
}
```

The problem is `wechat-uos` is explicitly using these older version of Electron and OpenSSL libraries. I have tried upgrading them to newer versions, and `wechat-uos` would just stop working.

To fix this problem we have to wait for the next official update of `wechat-uos`.

**Comment by xddxdd** [comment]
As suggested in https://github.com/NixOS/nixpkgs/issues/340954, dependency on OpenSSL 1.1 has been removed in the latest commit, by replacing `libuosdevicea.so` with this stub implementation: https://aur.archlinux.org/cgit/aur.git/tree/libuosdevicea.c?h=wechat-universal
